### ISSUE TITLE
Accept dynamic variable configured via command line

### ISSUE THREAD

**Issue by tanapoln** [wongnai/eastern#2]
Now, Easter CLI only accept 3 parameter like this:

    eastern deploy <kube-yml> <namespace> <image-tag>

And it map `<namespace>` and `<image-tag>` to variables `${NAMESPACE}` and `${IMAGE_TAG}` respectively.
Which is very strict and limit the capabilities of templating.

I would suggest to change the format of arguments accepted to be like this:

    eastern deploy <kube-yml> NAMESPACE=<namespace> IMAGE_TAG=<image-tag> ...`

which can accept any number of arguments!
I also suggest to put a constraint on parameter naming to this regex: `[A-Z0-9_]+`

By the way, it will break the old one, maybe, we could drop the support.

**Comment by whs** [comment]
This is in initial OSS release as `-s`
